basic:
    name: 'Dentrix Ascend Demo Testing'
    environments:
        production: 'https://www.dentrixascend.com/demo'
        staging: ''
        development: ''
    breakpoints:
        - 1920
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 40
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "\n  const $form = jQuery('#ascend-test-demo');\n\n  // Fill text inputs\n  $form.find('#firstName').val('HS1');\n  $form.find('#lastName').val('Test');\n  $form.find('#practiceName').val('HS1');\n  $form.find('#phoneNumber').val('1231231234');\n  $form.find('#emailAddress').val('test@testor.com');\n  $form.find('#zipCode').val('12345');\n\n  // Select dropdown: Organization Type = DSO\n  $form.find('#organizationType').val('DSO');\n\n  // Select dropdown: Reason for contact = I have a technical question\n  $form.find('#contactRequest').val('I have a technical question');\n\n  // Select radio: I have 8–20 locations\n  $form.find('input[name=\"numLocations\"][value=\"8-20\"]').prop('checked', true);\n\n  // Check consent checkbox\n  $form.find('#Email_and_Text_Opt_in_from_Form').prop('checked', true);\n\n  // Trigger form submit via the custom image button\n  $form.find('#customSubmit').click();\n\n"
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
