basic:
    name: 'Dentrix Ascend Demo Testing'
    environments:
        production: 'https://www.dentrixascend.com/demo'
        staging: ''
        development: ''
    breakpoints:
        - 1920
    pages:
        - /
    monitoring:
        days: {  }
        type: daily
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 20
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: "const firstDropdown = document.querySelector('.nav > li.dropdown');\n\n// Create and dispatch mouseover event\nconst mouseOverEvent = new MouseEvent('mouseover', {\n  view: window,\n  bubbles: true,\n  cancelable: true\n});\n\nif (firstDropdown) {\n  firstDropdown.dispatchEvent(mouseOverEvent);\n}"
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
